[package]
name = "mc-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
colored = "3.0.0"
reqwest = {version = "0.12.28", features = ["blocking"] }

